/**
 * Prints fresh local-development secrets in `.env.local` form:
 *
 *   pnpm zs:keygen >> .env.local
 *
 * Generates an ES256 signing key (`ZS_JWT_PRIVATE_KEY` / `ZS_JWT_KID`), the
 * editor-cookie secret and a cron secret. Never commit the output.
 */
import { randomBytes } from "node:crypto";
import { exportPKCS8, generateKeyPair } from "jose";

function envLine(name: string, value: string): string {
  // Double-quoted dotenv value; newlines become `\n` escapes that dotenv (and lib/tokens normalizePem) expand.
  return `${name}="${value.replace(/\n/g, "\\n")}"`;
}

async function main(): Promise<void> {
  const { privateKey } = await generateKeyPair("ES256", { extractable: true });
  const privatePem = await exportPKCS8(privateKey);
  const lines = [
    "# --- generated by scripts/keygen.ts ---",
    envLine("ZS_JWT_PRIVATE_KEY", privatePem.trim()),
    envLine("ZS_JWT_KID", "k1"),
    envLine("ZS_JWT_ISSUER", "zs"),
    envLine("ZS_EDITOR_COOKIE_SECRET", randomBytes(32).toString("base64")),
    envLine("CRON_SECRET", randomBytes(24).toString("base64url")),
    "",
  ];
  process.stdout.write(lines.join("\n"));
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
